#include<iostream>
#include<cmath>
#include<string>
#include<iomanip>
using namespace std;

class ScreenTime
{
private: int age;
float stime;
string name;

public: void introduction();
void instructions_to_user();
void greeting();
void AI_story_advice();
void conversation();
void put();
void result();
void final_thoughts();

};
void ScreenTime::introduction(){
cout<<"\n______________________________________\n\n";
cout<<"😃😃😃 Welcome to AI World!😃😃😃\n";
cout<<"\n\n________________________________________\n\n" ;
cout<<"\n•••••SCREEN TIME GUIDER•••••\n"<<endl;
cout<<"\n\n\n••••••••••••••••••••••••••••••••••••••\n\n\n"<<endl;
}
void ScreenTime::instructions_to_user() {
cout<<"\n🥺Please Note⚠️: \n You are speaking with an 🤖AI not a real person🚶‍♂️.\nThe output🔲 generated by the chatbot is pre-coded 👩‍💻keeping in mind 🤯 about the users of all ages.\nThis is 🚫not a medical 🏥advice\n" ;
}

void ScreenTime::greeting() {
cout<<"\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n";
cout<<"😃😃😃😃😃😃😃😃😃😃😃😃😃😃😃\n";
cout<<"🙋‍♂️Greetings from 🙋‍♀️YuAI👋,\nI'm a 🤖chatbot designed by Yuktha.S.Mayya👷‍♀️\nI'm here to guide your tech👨‍💻 journey✈️"<<endl;
cout<<"\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\n";
}

void ScreenTime::AI_story_advice() {
cout<<"\n°°°°°°°°°°°°My story°°°°°°°°°°°°\n"<<endl;
cout<<"\nOn the lush green environment🟩 a happy coder👷‍♀️ lived.\n🌱🌱🌱Green plants motivated her to build🧰 me on a particular Friday.\nThe sound🔊 of 🍃rustling of leaves🍃 from trees🌴🌳🌲, 🎶chirping🎶 of birds🐦🦚🦅🦜🐧 helped her complete me🤖.\n For the same reason during ancient📜 times⌛ sages lived in 🌳forests🌳👶🌳, we are inseparable👭 part of 🌋🏞️🌄nature🌄🏞️🌋.\nWe must spend quality time🕑 in lush green places.\n👀Watching Green plants🌱 can reduce 👁️ eye fatigue and strain.\nSo why to wait 🚦🏌️‍♂️when you can run🏃‍♀️🏃‍♂️happily in greenery🟩☘️🌳🌱! " <<endl;
cout<<"\n°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°\n";
}

void ScreenTime:: conversation() {
cout<<"\nOops, sorry🥺, I didn't ask anything about you...\n"<<endl;
cout<<"What can I call you? 😀: ";
cin.ignore();
getline(cin,name);
while(name.empty()){
cout<<"Please🥺🙏 enter a valid name💳: ";
getline(cin,name);
}
cout<<"What's your age😁: " ;
cin>>age;
while(age==0||age>110){
cout<<" Kindly do enter a valid age🙏: ";
cin>>age;
}
cout<<"Daily how many hours🕑 do you spend💰 on electronic gadgets👨‍💻? 😎Don't cheat me🦄, be honest🐰: " ;
cin>>stime;
cout<<"\n---------------------------------------\n\n";
cout<<name<<"😄!! you have used your electronic🖥️📺💻📳 gadgets👩‍💻 for "<<stime<<" hours😌😑 \n" ;
}

void ScreenTime::put() {
introduction();
instructions_to_user();
greeting();
AI_story_advice();
conversation();

if(age>0 && age<=6)
cout<<"\nDon't use mobile phone📵. \nYou should explore🧭 things,play with 👨‍👨‍👧‍👦parents,💑friends and 🧸🪀toys🧮. \nAlways be happy.\nEat a balanced 🥦🥣🍓🥝🥕diet\n" ;

else if(age>6 && age<13)
cout<<"\nDon't use screen 📵[[]]for more than 1 hour.\nYou should learn new things,play games🎲♟️⚽🏸🏑🏏,have fun with parents and friends.\nYou shouldn't get distracted 🙄with gadgets\n";

else if(age>=13 && age<20)
cout<<"\nOh teens! Don't idle time by creating account on Facebook, instagram, snapchat,etc...😢\nYou haven't even achieved great things🏆.\n You can spend time on social media after your jobs👷‍♀️.\nDon't think it's social behaviour to post/watch reels/shorts😦.\nRespect your parents😃, they have struggled and sacrificed too much for your well-being, try to understand them, don't argue🤼, don't ask for silly phone\nYou are more fortunate than crows,🦚🦆,dogs🐕 and other living beings,you have food🥗,water🚰,shelter🏘️,🚙\n" ;

else if(age>=20&&age<=45)
cout<<"You are stepping into your life's most precious time🎁👼.\nContribute to your nation🇮🇳 which helped you lead a happy life without any hindrance 🙏.\nNation needs youth. Avoid greediness\nAvoid excess social media.\nIt won't benefit you much\nSpend more time🕦 with your family than mobile📳📱\n";

else
cout<<"You have learnt🔰 more in your life's journey🛬. \nTeach👩‍🏫👨‍🏫 your children, relatives,family members 👨‍👨‍👧‍👦about right lifestyle, well-being,food habits🥕.\nAvoid excess phone or electronic gadgets, you know the reason very well... \nI don't know what to explain for elders like you...\nGive me your blessings🥺🙏. \nTeach 👨‍🏫our precious heritage, dharma to your children, grand children, relatives and explain them to honour our nation🇮🇳,rich culture, respect other traditions🎎 too.\n";
}

void ScreenTime:: result() {
int hours=round(stime);
switch(hours){
case 0: cout<<"\nWhat a nice🙂 habit!\nCongratulations🥳💐 for not becoming slaves of technology🎉🎊. Enjoy💃 your life!!\n\nIt is okay🆗 to own a technology, what is not okay🆗 is to be owned by technology- you have understood this very well😃\n You are not a nomophobia🤩.\n Be a naturalist ,ecologist🌳🌱";
break;
case 1: cout<<" \nOne hour screen time is quite too much😞🙁,but normal.\nYou are in green level🟢. \nDon't grumble much and try to concentrate🧠 on your works.";
break;
case 2: cout<<"\n😐What🤨!?\nTwo hours of scrolling reels,shorts isn't ideal.\nYou should limit your screen 📺🕧time.\n🚫Avoid continuous 🌊usage\nYou are in 🟡yellow level.\nDon't cry😭, i know it's difficult for you to achieve🎯.\nBut it's for your own good🏆.\n";
break;
case 3: cout<<"\nOh 3 hours🤨! \nThree hours on social media😡..not at all ideal.\nYou have to achieve more in your life🎯.Always spend quality time🕧\n You are in 🟠orange level.\nDon't worry😟, you can fix👩‍🔧 this";
break;
case 4:
case 5:
case 6: cout<<"\nYou are at pro level.\nSwitch on digital well-being from settings,track your apps and set timer⏲️ for each app.\nYou are in 🔴red dangerous level.\nTry to limit your screen time by setting a goal🎯 of using less screen📵 the next day,reward yourself if you achieve\n";
break;
case 7:
case 8:
case 9:
case 10:
case 11:
case 12:
case 13:
case 14:
case 15:
case 16:
case 17:
case 18:
case 19:
case 20:
case 21:
case 22:
case 23:
case 24:
cout<<"\n wait, woaahh🥴🙄 😱this is Elite 🛣️level😱. \nWhat do you get by watching YouTube shorts, instagram reels for 10 hours and more..🧐?\n\nYou will lose your concentration😵and eye-sight👓.\nDon't you know that excess screen usage hurts your heart ♥️and other internal organs🥺?\nYou aren't in any levels😟.\nYou are in worst 🤬case.\n Control yourself. \n📅Schedule your day.\n🛫🛫Lead a disciplined life.\n";
break; }
cout<<"\n\n_________________________________________________\n\n";
}
void ScreenTime::final_thoughts() {
cout<<"\nSo friends using screen for long time makes you more addicted and finally you would lose yourself to it.\nIf you have a beautiful family,parents,sisters, then it's a great fortune! Speak with them.\nDon't kill time seeing useless shorts,reels.\n\nIf you have important work on your mobile or laptop or computer,please take some breaks,follow 20-20-20 rule,blink fast after every 30 minutes.\nAlways use a bigger screen.\nAvoid staring at smaller screens like mobile phone.\nThese practices can help you lead a better lifestyle. \nAlways keep track of your screen time of all your gadgets.\nLead a life which would become an example for all.\nDon't get addicted to bad habits.\nBe humane.\nSpend time with nature, nature teaches many things.
\n ಸರ್ವೇಜನ: ಸುಖಿನೋರ್ಭವಂತು
\n. ಓಂ ಶಾಂತಿ ಶಾಂತಿ ಶಾಂತಿ\n";
}

int main()
{
ScreenTime st;
st.put();
st.result();
st.final_thoughts();
return 0;
}